### ISSUE TITLE
ArangoDB graph consideration

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store#264] opened 2017-02-16 18:47 UTC
I want to discuss some considerations for the ArangoDB event store. In short, [ArangoDB](https://www.arangodb.com/) is like MongoDB but much [better](https://www.arangodb.com/why-arangodb/arangodb-vs-mongodb/).

## 1. Should we use the graph feature?
I've created a some test data to play around with the graph. The test data contains 18 events and all events are stored in a collection named `event_storae` (like in MongoDB). Edges are stored in an `event_store_edges` collection. We have 9 aggregates and each aggregate has two events (`UserWasRegistered` and `UserEmailWasChanged`). First event series (1-9) are the `UserWasRegistered` events and second event series (10-18) are the `UserEmailWasChanged` events. The graph looks like this.

![graphs](https://cloud.githubusercontent.com/assets/3597436/23034389/f7ecb3c8-f47b-11e6-91ab-659695b0933c.png)

I could image that the graph feature could increase performance on retrieving events e.g. for aggregate 1 there exists the item id 1 and item id 10. You need *no* `sort` or `order by` stuff because the graph is ordered. You can create other edge collections to get other insights e.g. for projections like `MessageName` and you can also [add attributes to edges](http://www.slideshare.net/arangodb/handling-billions-of-edges-in-a-graph-database-gotolondon). I guess there are so much possibilities. Maybe `MetadataMatcher` could also rely on edges.

## 2. Is it possible to use graphs?
One problem is to find the id of the previous event to add a new edge so that all the events are in order. The second problem is, find the previous event for an aggregate if any, to create the edge. I guess we can do all this in a transaction, but is it fast? Is it possible to find a previous event which belongts to this event, because the event store don't know anything about aggregates right?

## 3. Should the graph only be a projection
To avoid the problems from 2 we could implement the event store like the schema from `pdo-event-store` and use only projections to build a graph. But what I want to achieve is, that the event store uses the graph to load events (`load`, `loadReverse`). I don't know if a graph is faster than an order by if we can't calculate which events belongs to one aggregate e.g. event 4 and 13.

I guess it's hard to answer these things but maybe some brainstorming could also help to find a good and reasonable way.

**Comment by prolic** [comment] 2017-02-19 11:08
The graph should be a little slower compared to an order by query. The strength of graph db's comes with queries on relations (compared to joins on rdbms), not on simple stuff like query a single table / collection.

The graph feature is however really nice for stuff like event-store-ui or projections. But you can prove me wrong with a benchmark, if you like.

**Comment by codeliner** [comment] 2017-02-19 16:53
Same thoughts here. Not sure if a graph can provide unique constraints for the combination aggregate type + aggregate version for example.

A document store fits very well with the use case of writing events to a stream. Unfortunately, mongoDB does not provide ACID for more than one document and no built-in auto-increment sequence.
If ArangoDB provides the required features as a document store we should use that.
The graph stuff however, is very very interesting for projections.

**Comment by codeliner** [comment] 2017-02-19 19:48
I have to revert my previous comment. @sandrokeil maybe your idea is really great. I'm not sure because I'm not a graph expert but... 

I often describe a message flow including the commands so maybe they are the missing piece of the puzzle. I try to explain:

First post request by client:
command1 -> new aggregate is born -> event1 (caused by: command1) -> state.version1 (caused by: event1)

client query new aggregate state, make decision, trigger new command:
state.version1 -> make decision based on state -> command2 (based on: state.version1)

Second post request by client:
command2 -> aggregate handle command 
          |_ event2 (caused by command2) \___ state.version3 (caused by event2 & event3)
          |_ event3 (caused by command2) /


This is a graph!

**command1** (the message is the node) -> **CreateAggregate** (message name is the relationship) -> **event1** (event is the target node of the relationship) -> **AggregateWasCreated** (again message name is the relationship) -> **state.version1** (next node, this time state identified by version 1) -> **command2** (message node) -> **DoSomething** (relationship) -> **event2** (message node) &
-> **command2** (message node) -> **DoSomething** (relationship) -> **event3** (message node)
-> **SometingWasDone1** (relationship) -> **state.version3** (state node, version3 because one transaction with two events as result) &
-> **SomethingWasDone2** (relationship to same state node) -> **state.version3**

and so on...

All messages have the `aggregate id` in either the payload (command) or metadata (event) and of course also state is identified by aggregate id.
So `aggregate id` has to be a property of every node (message or state).

message nodes are identified by their UUIDs 
state nodes are identified by `aggregate id` + `state version`

Query current state: Find the latest state node of `aggregateId`
Replay: Find all event nodes with property `aggregateId`
System monitoring: watch the graph of an aggregate and you see everything :D
temporal queries: Query message nodes by `created_at` and Relationship(s)
... 

So instead of an event store you would have a new kind of store which persists the next part of an aggregate graph:
- command
- event[]
- state

@sandrokeil We should play with this idea. In prooph/micro it would be easy to collect all three nodes and pass them to the store.

**Comment by prolic** [comment] 2018-12-25 08:11
I'm closing this issue now, it's almost 2 years old. There is a WIP implementation for ArangoDB [here](https://github.com/sandrokeil/arangodb-event-store)

**Comment by prolic** [comment] 2020-02-08 03:49
Closing due to lack of activity.

**Closed by prolic** 2020-02-08 03:49 UTC
Labels: question
